name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile all C++ solutions
        run: |
          set -e
          # Compile codeforces_practice
          for file in codeforces_practice/*/*.cpp; do
            echo "Compiling $file"
            g++ -std=gnu++17 -O2 -Wall -Wextra "$file" -o "${file%.cpp}.out"
          done

          # Compile codeforces_contests
          for file in codeforces_contests/*/*.cpp; do
            echo "Compiling $file"
            g++ -std=gnu++17 -O2 -Wall -Wextra "$file" -o "${file%.cpp}.out"
          done
